const API_BASE_URL = (window.BEAM_ANALYZER_API_URL || '').replace(/\/$/, '');

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const clone=x=>JSON.parse(JSON.stringify(x));
const examples={
 simple:{units:'SI',spans:[{id:1,length:8,E:200,I:1e8}],supports:[{id:1,type:'pin',position:0,settlement:0},{id:2,type:'roller',position:8,settlement:0}],loads:[{id:1,type:'point',value:-10,value2:0,from:4,to:4}]},
 udl:{units:'SI',spans:[{id:1,length:6,E:200,I:1e8}],supports:[{id:1,type:'pin',position:0,settlement:0},{id:2,type:'roller',position:6,settlement:0}],loads:[{id:1,type:'udl',value:-10,value2:-10,from:0,to:6}]},
 cantilever:{units:'SI',spans:[{id:1,length:4,E:200,I:1e8}],supports:[{id:1,type:'fixed',position:0,settlement:0}],loads:[{id:1,type:'point',value:-20,value2:0,from:4,to:4}]}
};
let model=loadLocal()||clone(examples.simple),result=null,unit=model.units||'SI',past=[],future=[],dark=localStorage.getItem('ba-dark')==='1';
let viewMode='select',zoom=1,showGrid=false,showDims=true,panX=0,panY=0,panStart=null,solveTimer=null,solveSeq=0,activeController=null;
function isModel(x){return !!x&&Array.isArray(x.spans)&&x.spans.length>0&&Array.isArray(x.supports)&&Array.isArray(x.loads)}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem('ba-model'));return isModel(x)?x:null}catch{return null}}
function saveLocal(){try{localStorage.setItem('ba-model',JSON.stringify(model))}catch{}}
function fmt(v,d=3){v=Number(v);if(!Number.isFinite(v))return'—';if(Math.abs(v)<1e-12)return'0';return new Intl.NumberFormat(undefined,{maximumFractionDigits:d}).format(v)}
function len(){return model.spans.reduce((a,s)=>a+Number(s.length||0),0)}
function id(arr){return arr.length?Math.max(...arr.map(x=>+x.id||0))+1:1}
function unitText(k){const si=unit==='SI';return({length:si?'m':'ft',force:si?'kN':'kip',moment:si?'kN·m':'kip·ft',load:si?'kN/m':'kip/ft',defl:si?'mm':'in'})[k]}
const CONV={length:3.28083989501312,force:0.22480894387096,moment:0.73756214927727,load:0.068521765856,defl:0.0393700787401575,E:145.03773773,I:1/416231.4256};
function convertModelUnits(next){if(next===unit)return;const toImp=unit==='SI'&&next==='imperial', f=(k)=>toImp?CONV[k]:1/CONV[k];model.spans.forEach(s=>{s.length=+s.length*f('length');s.E=+s.E*f('E');s.I=+s.I*f('I')});model.supports.forEach(s=>{s.position=+s.position*f('length');s.settlement=+s.settlement*f('defl')});model.loads.forEach(l=>{l.from=+l.from*f('length');l.to=+l.to*f('length');l.value=+l.value*f(l.type==='udl'?'load':l.type==='moment'?'moment':'force');l.value2=+l.value2*f(l.type==='udl'?'load':l.type==='moment'?'moment':'force')});unit=next;model.units=next}
function setStatus(text,state='ready'){const el=$('#status');el.innerHTML=`<span class="statusDot ${state}"></span><span>${text}</span>`}
function mutate(fn){past.push(clone(model));if(past.length>50)past.shift();future=[];fn();result=null;saveLocal();render();scheduleSolve()}
function undo(){if(!past.length)return;future.push(clone(model));model=past.pop();unit=model.units||'SI';result=null;render();scheduleSolve()}
function redo(){if(!future.length)return;past.push(clone(model));model=future.pop();unit=model.units||'SI';result=null;render();scheduleSolve()}
function renderInputs(){
 $('#spanRows').innerHTML=model.spans.map((s,i)=>`<tr><td>${i+1}</td><td><input data-s="${s.id}" data-k="length" type="number" step="any" value="${s.length}"></td><td><input data-s="${s.id}" data-k="E" type="number" step="any" value="${s.E}"></td><td><input data-s="${s.id}" data-k="I" type="number" step="any" value="${s.I}"></td><td><button class="remove" data-del-span="${s.id}">×</button></td></tr>`).join('');
 $('#supportRows').innerHTML=model.supports.map(s=>`<tr><td>${s.id}</td><td><select data-sup="${s.id}" data-k="type"><option value="pin" ${s.type==='pin'?'selected':''}>Pin</option><option value="roller" ${s.type==='roller'?'selected':''}>Roller</option><option value="fixed" ${s.type==='fixed'?'selected':''}>Fixed</option></select></td><td><input data-sup="${s.id}" data-k="position" type="number" step="any" value="${s.position}"></td><td><input data-sup="${s.id}" data-k="settlement" type="number" step="any" value="${s.settlement||0}"></td><td><button class="remove" data-del-sup="${s.id}">×</button></td></tr>`).join('');
 $('#loadRows').innerHTML=model.loads.map(l=>`<tr><td>${l.id}</td><td><select data-load="${l.id}" data-k="type"><option value="point" ${l.type==='point'?'selected':''}>Point</option><option value="udl" ${l.type==='udl'?'selected':''}>UDL / varying</option><option value="moment" ${l.type==='moment'?'selected':''}>Moment</option></select></td><td><input data-load="${l.id}" data-k="value" type="number" step="any" value="${l.value}"></td><td><input data-load="${l.id}" data-k="value2" type="number" step="any" value="${l.value2??0}"></td><td><input data-load="${l.id}" data-k="from" type="number" step="any" value="${l.from}"></td><td><input data-load="${l.id}" data-k="to" type="number" step="any" value="${l.to??l.from}"></td><td><button class="remove" data-del-load="${l.id}">×</button></td></tr>`).join('');
 $$('#spanRows input').forEach(e=>e.onchange=()=>mutate(()=>{const s=model.spans.find(x=>x.id==e.dataset.s);if(s)s[e.dataset.k]=+e.value}));
 $$('#supportRows input,#supportRows select').forEach(e=>e.onchange=()=>mutate(()=>{const s=model.supports.find(x=>x.id==e.dataset.sup);if(s)s[e.dataset.k]=e.tagName==='SELECT'?e.value:+e.value}));
 $$('#loadRows input,#loadRows select').forEach(e=>e.onchange=()=>mutate(()=>{const l=model.loads.find(x=>x.id==e.dataset.load);if(l)l[e.dataset.k]=e.tagName==='SELECT'?e.value:+e.value}));
 $$('[data-del-span]').forEach(b=>b.onclick=()=>mutate(()=>{if(model.spans.length>1)model.spans=model.spans.filter(s=>s.id!=b.dataset.delSpan)}));
 $$('[data-del-sup]').forEach(b=>b.onclick=()=>mutate(()=>{model.supports=model.supports.filter(s=>s.id!=b.dataset.delSup)}));
 $$('[data-del-load]').forEach(b=>b.onclick=()=>mutate(()=>{model.loads=model.loads.filter(l=>l.id!=b.dataset.delLoad)}));
}
function supportSvg(s,x,y){
 if(s.type==='fixed')return `<g><line x1="${x-14}" y1="${y-32}" x2="${x-14}" y2="${y+16}" class="fixedWall"/><path d="M ${x-14} ${y-28} l-10 6 m10 2 l-10 6 m10 2 l-10 6 m10 2 l-10 6 m10 2 l-10 6" class="hatch"/><line x1="${x-14}" y1="${y-32}" x2="${x}" y2="${y}" class="beamConnector"/></g>`;
 const roller=s.type==='roller';
 let out=`<path d="M ${x-18} ${y+11} L ${x} ${y-10} L ${x+18} ${y+11} Z" class="supportTriangle"/>`;
 if(roller) out+=`<circle cx="${x-8}" cy="${y+18}" r="5.3" class="rollerWheel"/><circle cx="${x+8}" cy="${y+18}" r="5.3" class="rollerWheel"/><line x1="${x-24}" y1="${y+27}" x2="${x+24}" y2="${y+27}" class="groundLine"/><path d="M ${x-20} ${y+27} l-6 7 m13-7 l-6 7 m13-7 l-6 7 m13-7 l-6 7" class="hatch"/>`;
 else out+=`<line x1="${x-23}" y1="${y+12}" x2="${x+23}" y2="${y+12}" class="groundLine"/><path d="M ${x-19} ${y+12} l-6 7 m12-7 l-6 7 m12-7 l-6 7 m12-7 l-6 7" class="hatch"/>`;
 return out;
}
function renderBeam(){
 const W=1200,H=300,pad=72,y=112,L=Math.max(len(),1),x=p=>pad+(p/L)*(W-2*pad);
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Beam model"><defs><marker id="arrowRed" markerWidth="9" markerHeight="9" refX="4.5" refY="4.5" orient="auto"><path d="M0,0 L9,4.5 L0,9 z" fill="#ef4444"/></marker><marker id="arrowPurple" markerWidth="9" markerHeight="9" refX="4.5" refY="4.5" orient="auto"><path d="M0,0 L9,4.5 L0,9 z" fill="#8b5cf6"/></marker></defs>`;
 if(showDims){svg+=`<line x1="${pad}" y1="216" x2="${W-pad}" y2="216" class="dimLine"/><line x1="${pad}" y1="207" x2="${pad}" y2="224" class="dimLine"/><line x1="${W-pad}" y1="207" x2="${W-pad}" y2="224" class="dimLine"/><text x="${W/2}" y="238" text-anchor="middle" class="dimText">${fmt(L)} ${unitText('length')}</text>`;let start=0;for(const s of model.spans){const xx=x(start+s.length/2);svg+=`<text x="${xx}" y="202" text-anchor="middle" class="spanText">${fmt(s.length)} ${unitText('length')}</text>`;start+=+s.length}}
 svg+=`<line x1="${pad}" y1="${y}" x2="${W-pad}" y2="${y}" class="beamLine"/>`;
 model.supports.forEach((s,i)=>{const xx=x(s.position);svg+=`<g class="drag supportDrag" data-drag="support" data-id="${s.id}">${supportSvg(s,xx,y)}<circle cx="${xx}" cy="${y-4}" r="10" class="supportBadge"/><text x="${xx}" y="${y}" text-anchor="middle" dominant-baseline="middle" class="supportNumber">${i+1}</text><text x="${xx}" y="${y+55}" text-anchor="middle" class="supportText">${s.type==='fixed'?'Fixed':s.type==='roller'?'Roller':'Pin'} · ${fmt(s.position)} ${unitText('length')}</text></g>`});
 model.loads.forEach(l=>{if(l.type==='point'){const xx=x(l.from);svg+=`<g class="drag loadDrag" data-drag="load" data-id="${l.id}"><line x1="${xx}" y1="35" x2="${xx}" y2="${y-7}" class="pointLoad" marker-end="url(#arrowRed)"/><text x="${xx}" y="24" text-anchor="middle" class="loadText redText">${fmt(Math.abs(l.value))} ${unitText('force')}</text></g>`}else if(l.type==='moment'){const xx=x(l.from);svg+=`<g class="drag loadDrag" data-drag="load" data-id="${l.id}"><path d="M ${xx+14} ${y-17} A 22 22 0 1 0 ${xx-14} ${y+17}" class="momentArc" marker-end="url(#arrowPurple)"/><text x="${xx}" y="${y-34}" text-anchor="middle" class="loadText purpleText">${fmt(l.value)} ${unitText('moment')}</text></g>`}else{const a=x(l.from),b=x(l.to);svg+=`<g><line x1="${a}" y1="53" x2="${b}" y2="53" class="udlLine"/><path d="M ${a} 53 V 82 M ${(a+b)/2} 53 V 82 M ${b} 53 V 82" class="udlTicks"/><text x="${(a+b)/2}" y="43" text-anchor="middle" class="loadText redText">${fmt(l.value)} → ${fmt(l.value2)} ${unitText('load')}</text></g>`}});
 svg+=`<text x="${pad}" y="274" class="axisText">0 ${unitText('length')}</text><text x="${W-pad}" y="274" text-anchor="end" class="axisText">${fmt(L)} ${unitText('length')}</text></svg>`;
 $('#beamCanvas').innerHTML=svg;$('#beamCanvas').style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;
 $$('#beamCanvas [data-drag="support"]').forEach(g=>g.onpointerdown=e=>viewMode==='select'&&dragItem(e,'support',+g.dataset.id));$$('#beamCanvas [data-drag="load"]').forEach(g=>g.onpointerdown=e=>viewMode==='select'&&dragItem(e,'load',+g.dataset.id));
}
function dragItem(ev,type,itemId){ev.preventDefault();const svg=$('#beamCanvas svg'),rect=svg.getBoundingClientRect(),W=1200,pad=72,L=Math.max(len(),1),before=clone(model);const move=e=>{const px=Math.max(pad,Math.min(W-pad,(e.clientX-rect.left)/rect.width*W));let p=(px-pad)/(W-2*pad)*L;p=Math.round(p*100)/100;if(type==='support'){const s=model.supports.find(x=>x.id===itemId);if(s)s.position=p}else{const l=model.loads.find(x=>x.id===itemId);if(l){if(l.type==='udl'){const width=Math.max(0,l.to-l.from);l.from=p;l.to=Math.min(L,Math.round((p+width)*100)/100)}else{l.from=p;l.to=p}}}renderBeam()};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);if(JSON.stringify(before)!==JSON.stringify(model)){past.push(before);if(past.length>50)past.shift();future=[];saveLocal();result=null;setStatus('Updating…','busy');scheduleSolve()}};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)}
function validate(){const e=[],L=len();if(!L||L<=0)e.push('Total beam length must be greater than zero.');if(model.spans.some(s=>!s.length||s.length<=0))e.push('Every span needs a positive length.');if(model.spans.some(s=>!s.E||s.E<=0||!s.I||s.I<=0))e.push('Every span needs positive E and I.');if(!model.supports.length)e.push('Add at least one support.');for(const s of model.supports)if(s.position<0||s.position>L)e.push(`Support ${s.id} is outside the beam.`);for(const l of model.loads)if(l.from<0||l.from>L||l.to<0||l.to>L||l.to<l.from)e.push(`Load ${l.id} has an invalid position/range.`);return[...new Set(e)]}
function payload(){return{units:unit,spans:model.spans.map(s=>({length:+s.length,E:+s.E,I:+s.I})),supports:model.supports.map(s=>({type:s.type,position:+s.position,settlement:+(s.settlement||0)})),loads:model.loads.map(l=>l.type==='point'?{type:'point',magnitude:+l.value,position:+l.from}:l.type==='moment'?{type:'moment',magnitude:+l.value,position:+l.from}:{type:'udl',start:+l.value,end:+l.value2,from:+l.from,to:+l.to})}}
function normalizeSeries(v){if(!v)return[];if(Array.isArray(v))return v.map(p=>Array.isArray(p)?{x:+p[0],y:+p[1]}:{x:+(p.x??p.position??p[0]),y:+(p.y??p.value??p[1])}).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));if(typeof v==='object'&&Array.isArray(v.x)&&Array.isArray(v.y))return v.x.map((x,i)=>({x:+x,y:+v.y[i]})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));return[]}
function getSeries(diagrams,keys){for(const k of keys){const a=normalizeSeries(diagrams?.[k]);if(a.length)return a}return[]}
function extreme(a){return a.length?a.reduce((m,p)=>Math.abs(p.y)>Math.abs(m.y)?p:m,a[0]):null}
function nearest(series,x){return series.reduce((best,p)=>Math.abs(p.x-x)<Math.abs(best.x-x)?p:best,series[0])}
function scaleFns(w,h,pad,minY,maxY,L){const sx=x=>pad+(x/L)*(w-2*pad),sy=y=>h-pad-(y-minY)/(maxY-minY||1)*(h-2*pad);return{sx,sy}}
function pathFor(series,fn){return series.map((p,i)=>`${i?'L':'M'} ${fn.sx(p.x).toFixed(1)} ${fn.sy(p.y).toFixed(1)}`).join(' ')}
function areaFor(series,fn,zero){if(!series.length)return'';return `M ${fn.sx(series[0].x).toFixed(1)} ${fn.sy(zero).toFixed(1)} L ${series.map(p=>`${fn.sx(p.x).toFixed(1)} ${fn.sy(p.y).toFixed(1)}`).join(' L ')} L ${fn.sx(series.at(-1).x).toFixed(1)} ${fn.sy(zero).toFixed(1)} Z`}
function featureMarks(series,fn,h,pad,minY,maxY,L){if(!$('#featureToggle')?.checked||!series.length)return'';let out='';const base=fn.sy(0);model.supports.forEach(s=>{if(s.position<0||s.position>L)return;const p=nearest(series,s.position),xx=fn.sx(p.x);out+=`<line x1="${xx}" y1="${pad}" x2="${xx}" y2="${h-pad}" class="featureGuide"/><path d="M ${xx-7} ${base+4} L ${xx} ${base-7} L ${xx+7} ${base+4} Z" class="featureSupport"/>`});model.loads.forEach(l=>{if(l.type==='point'||l.type==='moment'){const p=nearest(series,l.from),xx=fn.sx(p.x),yy=fn.sy(p.y);out+=`<line x1="${xx}" y1="${pad}" x2="${xx}" y2="${h-pad}" class="featureGuide"/>`;if(l.type==='point')out+=`<rect x="${xx-5}" y="${yy-5}" width="10" height="10" rx="2" transform="rotate(45 ${xx} ${yy})" class="featureLoad"/>`;else out+=`<circle cx="${xx}" cy="${yy}" r="5" class="featureMoment"/>`}else{const a=nearest(series,l.from),b=nearest(series,l.to);if(a&&b)out+=`<line x1="${fn.sx(a.x)}" y1="${pad}" x2="${fn.sx(a.x)}" y2="${h-pad}" class="featureLoadLine"/><line x1="${fn.sx(b.x)}" y1="${pad}" x2="${fn.sx(b.x)}" y2="${h-pad}" class="featureLoadLine"/>`}});return out}
function chart(title,series,kind,empty='No series returned.'){
 const card=document.createElement('section');card.className=`chart kind-${kind}`;if(!series.length){card.innerHTML=`<div class="chartHeader"><h3>${title}</h3></div><div class="chartEmpty">${empty}</div>`;return card.outerHTML}
 const w=1100,h=330,pad=56,L=Math.max(len(),1),ys=series.map(p=>p.y),rawMin=Math.min(...ys),rawMax=Math.max(...ys),range=Math.max(Math.abs(rawMin),Math.abs(rawMax),1e-9),min=Math.min(0,rawMin-range*.06),max=Math.max(0,rawMax+range*.06),fn=scaleFns(w,h,pad,min,max,L),zero=fn.sy(0),d=pathFor(series,fn),area=areaFor(series,fn,0);const stroke=kind==='moment'?'#28d7b0':kind==='defl'?'#f59e0b':kind==='axial'?'#8b5cf6':kind==='rotation'?'#e879f9':'#3b8cff';
 const ticks=[0,.25,.5,.75,1].map(t=>{const val=min+(max-min)*t,yy=fn.sy(val);return `<line x1="${pad}" y1="${yy}" x2="${w-pad}" y2="${yy}" class="chartGridLine"/><text x="${pad-9}" y="${yy+3}" text-anchor="end" class="chartTick">${fmt(val,2)}</text>`}).join('');
 const xTicks=[0,.25,.5,.75,1].map(t=>{const xx=pad+t*(w-2*pad),val=L*t;return `<line x1="${xx}" y1="${h-pad}" x2="${xx}" y2="${h-pad+5}" class="chartAxis"/><text x="${xx}" y="${h-pad+20}" text-anchor="middle" class="chartTick">${fmt(val,2)}</text>`}).join('');
 const marks=featureMarks(series,fn,h,pad,min,max,L),pts=JSON.stringify(series).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/'/g,'&apos;');
 card.innerHTML=`<div class="chartHeader"><h3>${title}</h3><button class="collapseChart" type="button">Collapse</button></div><div class="chartBody"><div class="chartBox"><svg viewBox="0 0 ${w} ${h}" data-series='${pts}' data-len="${L}" data-pad="${pad}" data-min="${min}" data-max="${max}" data-kind="${kind}"><g>${ticks}</g><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}" class="chartAxis"/><line x1="${pad}" y1="${zero}" x2="${w-pad}" y2="${zero}" class="chartZero"/><path d="${area}" class="chartArea" fill="${stroke}"/><path d="${d}" class="chartLine" stroke="${stroke}"/><g class="features">${marks}</g><g>${xTicks}</g><text x="${w/2}" y="${h-7}" text-anchor="middle" class="chartAxisTitle">Position (${unitText('length')})</text><text x="16" y="${h/2}" transform="rotate(-90 16 ${h/2})" text-anchor="middle" class="chartAxisTitle">${title.replace(' diagram','')}</text><circle class="hoverDot" r="4" cx="-20" cy="-20"/><line class="hoverGuide" x1="-20" y1="${pad}" x2="-20" y2="${h-pad}"/></svg><div class="chartTooltip"></div></div></div>`;
 return card.outerHTML;
}
function attachChartInteractions(){
 $$('#charts .chart').forEach(card=>{const svg=card.querySelector('svg');if(!svg)return;const box=card.querySelector('.chartBox'),tip=card.querySelector('.chartTooltip'),dot=svg.querySelector('.hoverDot'),guide=svg.querySelector('.hoverGuide'),series=JSON.parse(svg.dataset.series),L=+svg.dataset.len,pad=+svg.dataset.pad,w=1100,h=330,min=+svg.dataset.min,max=+svg.dataset.max,fn=scaleFns(w,h,pad,min,max,L),kind=svg.dataset.kind;svg.addEventListener('pointermove',e=>{const r=svg.getBoundingClientRect(),rx=(e.clientX-r.left)/r.width*w;let x=Math.max(0,Math.min(L,(rx-pad)/(w-2*pad)*L));const p=nearest(series,x),sx=fn.sx(p.x),sy=fn.sy(p.y);dot.setAttribute('cx',sx);dot.setAttribute('cy',sy);guide.setAttribute('x1',sx);guide.setAttribute('x2',sx);guide.style.display='block';dot.style.display='block';const label=kind==='shear'||kind==='axial'?'Force':kind==='moment'?'Moment':kind==='defl'?'Deflection':'Rotation';const u=kind==='shear'||kind==='axial'?'force':kind==='moment'?'moment':kind==='defl'?'defl':'force';tip.style.display='block';tip.innerHTML=`<b>x:</b> ${fmt(p.x)} ${unitText('length')}<br><b>${label}:</b> ${fmt(p.y)} ${unitText(u)}`;tip.style.left=`${Math.min(box.clientWidth-150,Math.max(5,sx/w*box.clientWidth+10))}px`;tip.style.top=`${Math.max(5,sy/h*box.clientHeight-35)}px`});svg.addEventListener('pointerleave',()=>{tip.style.display='none';dot.style.display='none';guide.style.display='none'});card.querySelector('.collapseChart').onclick=()=>{card.classList.toggle('collapsed');card.querySelector('.collapseChart').textContent=card.classList.contains('collapsed')?'Expand':'Collapse'}})
}
function renderResults(){
 if(!result){$('#solvedBadge').textContent='Waiting';$('#solvedBadge').classList.remove('solved');$('#reactions').className='tableWrap empty';$('#reactions').textContent='—';$('#charts').innerHTML='';return}
 const d=result.diagrams||{},v=getSeries(d,['shear','sfd','V']),m=getSeries(d,['moment','bmd','M']),def=getSeries(d,['deflection','displacement','delta','y']),rot=getSeries(d,['rotation','slope','theta']),ax=getSeries(d,['axial','normal','axialForce']);const ev=extreme(v),em=extreme(m),ed=extreme(def);
 $('#solvedBadge').textContent='Solved';$('#solvedBadge').classList.add('solved');$('#maxV').textContent=ev?`${fmt(Math.abs(ev.y))} ${unitText('force')}`:'—';$('#maxVPos').textContent=ev?`at ${fmt(ev.x)} ${unitText('length')}`:'—';$('#maxM').textContent=em?`${fmt(Math.abs(em.y))} ${unitText('moment')}`:'—';$('#maxMPos').textContent=em?`at ${fmt(em.x)} ${unitText('length')}`:'—';$('#maxD').textContent=ed?`${fmt(Math.abs(ed.y))} ${unitText('defl')}`:'—';$('#maxDPos').textContent=ed?`at ${fmt(ed.x)} ${unitText('length')}`:'—';$('#maxN').textContent=ax.length?`${fmt(Math.abs(extreme(ax).y))} ${unitText('force')}`:'0';
 const rs=result.reactions||[];$('#reactions').className='tableWrap';$('#reactions').innerHTML=`<table><thead><tr><th>Type</th><th>Position</th><th>Vertical</th><th>Moment</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${r.type||'support'}</td><td>${fmt(r.position)} ${unitText('length')}</td><td>${fmt(r.vertical??r.v??0)} ${unitText('force')}</td><td>${fmt(r.moment??0)} ${unitText('moment')}</td></tr>`).join('')}</tbody></table>`;
 $('#charts').innerHTML=chart('Shear force diagram (SFD)',v,'shear')+chart('Bending moment diagram (BMD)',m,'moment')+chart('Axial force diagram (AFD)',ax,'axial','No axial series.')+chart('Deflection diagram',def,'defl')+chart('Rotation / slope',rot,'rotation');attachChartInteractions();
}
function render(){renderInputs();renderBeam();renderResults();$$('[data-unit]').forEach(b=>b.classList.toggle('active',b.dataset.unit===unit));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===viewMode));$('#gridBtn').classList.toggle('active',showGrid);$('#dimsBtn').classList.toggle('active',showDims);$('#zoomValue').textContent=`${Math.round(zoom*100)}%`;$('#themeBtn').textContent=dark?'☀':'☾';$('#beamViewport').classList.toggle('gridOn',showGrid)}
function scheduleSolve(delay=420){clearTimeout(solveTimer);setStatus('Updating…','busy');solveTimer=setTimeout(solveNow,delay)}
async function solveNow(){const seq=++solveSeq;const errs=validate();$('#validation').classList.toggle('hidden',!errs.length);$('#validation').innerHTML=errs.length?`<b>Fix these:</b><ul>${errs.map(x=>`<li>${x}</li>`).join('')}</ul>`:'';if(errs.length){setStatus('Needs input','error');return}if(activeController)activeController.abort();activeController=new AbortController();$('#error').classList.add('hidden');try{setStatus('Solving…','busy');const r=await fetch(`${API_BASE_URL}/api/beam/solve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload()),signal:activeController.signal});const data=await r.json().catch(()=>({detail:'Server returned invalid JSON.'}));if(seq!==solveSeq)return;if(!r.ok){let msg=data.detail||`Analysis failed (${r.status})`;if(Array.isArray(data.issues)&&data.issues.length)msg+=' '+data.issues.map(i=>`${i.path||'request'}: ${i.message||'invalid value'}`).join(' · ');if(r.status===401)msg='StructureCalcs rejected the API key. Check your .env key.';if(r.status===429){const retry=r.headers.get('retry-after');if(retry)msg+=` Retry after ${retry} seconds.`}throw Error(msg)}result=data;renderResults();saveLocal();setStatus('Live · solved','ready')}catch(e){if(e.name==='AbortError')return;$('#error').textContent=e.message;$('#error').className='message error';$('#error').classList.remove('hidden');setStatus('Analysis error','error')}finally{if(seq===solveSeq)activeController=null}}
function report(){if(!result){scheduleSolve(0);return}const r=result.reactions||[];const w=window.open('about:blank','_blank');if(!w)return;w.document.write(`<!doctype html><html><head><title>Beam Analyzer Report</title><style>body{font:14px Arial;max-width:900px;margin:30px auto;color:#172033}table{border-collapse:collapse;width:100%;margin:12px 0 24px}th,td{border:1px solid #ccc;padding:7px;text-align:left}.grid{display:flex;gap:12px}.box{border:1px solid #ccc;padding:12px;flex:1}</style></head><body><h1>Beam Analyzer Calculation Report</h1><p>Generated ${new Date().toLocaleString()} · Units: ${unit}</p><p><strong>by Md. Hasanuzzaman Himel (RUET CE' 24)</strong></p><h2>Beam</h2><p>Total length: ${fmt(len())} ${unitText('length')}</p><h2>Supports</h2><table><tr><th>Type</th><th>Position</th><th>Settlement</th></tr>${model.supports.map(s=>`<tr><td>${s.type}</td><td>${fmt(s.position)}</td><td>${fmt(s.settlement||0)} ${unitText('defl')}</td></tr>`).join('')}</table><h2>Loads</h2><table><tr><th>Type</th><th>Value 1</th><th>Value 2</th><th>From</th><th>To</th></tr>${model.loads.map(l=>`<tr><td>${l.type}</td><td>${fmt(l.value)}</td><td>${fmt(l.value2||0)}</td><td>${fmt(l.from)}</td><td>${fmt(l.to)}</td></tr>`).join('')}</table><h2>Reactions</h2><table><tr><th>Type</th><th>Position</th><th>Vertical</th><th>Moment</th></tr>${r.map(x=>`<tr><td>${x.type||''}</td><td>${fmt(x.position)}</td><td>${fmt(x.vertical??x.v??0)} ${unitText('force')}</td><td>${fmt(x.moment??0)} ${unitText('moment')}</td></tr>`).join('')}</table><h2>Summary</h2><div class="grid"><div class="box">Max |V|<br><b>${$('#maxV').textContent}</b></div><div class="box">Max |M|<br><b>${$('#maxM').textContent}</b></div><div class="box">Max |δ|<br><b>${$('#maxD').textContent}</b></div></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
$('#addSpan').onclick=()=>mutate(()=>model.spans.push({id:id(model.spans),length:4,E:200,I:1e8}));$('#addSupport').onclick=()=>mutate(()=>model.supports.push({id:id(model.supports),type:'roller',position:len()/2,settlement:0}));$$('[data-add]').forEach(b=>b.onclick=()=>mutate(()=>{const L=len(),t=b.dataset.add,i=id(model.loads);model.loads.push(t==='point'?{id:i,type:t,value:-10,value2:0,from:L/2,to:L/2}:t==='moment'?{id:i,type:t,value:10,value2:0,from:L/2,to:L/2}:{id:i,type:t,value:-5,value2:-5,from:0,to:L})}));
$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#newBtn').onclick=()=>{past=[];future=[];model=clone(examples.simple);unit='SI';result=null;saveLocal();render();scheduleSolve(100)};$$('.example').forEach(b=>b.onclick=()=>{model=clone(examples[b.dataset.example]);unit='SI';result=null;saveLocal();render();scheduleSolve(100)});$('#themeBtn').onclick=()=>{dark=!dark;document.documentElement.classList.toggle('dark',dark);localStorage.setItem('ba-dark',dark?'1':'0');render()};$$('[data-unit]').forEach(b=>b.onclick=()=>{if(b.dataset.unit===unit)return;past.push(clone(model));if(past.length>50)past.shift();future=[];convertModelUnits(b.dataset.unit);result=null;saveLocal();render();scheduleSolve(100)});
$('#saveBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(model,null,2)],{type:'application/json'}));a.download='beam-model.json';a.click()};$('#loadInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!isModel(x))throw Error();model=x;unit=x.units||'SI';result=null;saveLocal();render();scheduleSolve(100)}catch{$('#error').textContent='Invalid model JSON.';$('#error').className='message error';$('#error').classList.remove('hidden')}};r.readAsText(f)};
$('#shareBtn').onclick=async()=>{const u=new URL(location.href);u.hash='model='+btoa(unescape(encodeURIComponent(JSON.stringify(model))));try{await navigator.clipboard.writeText(u.href);$('#error').textContent='Share link copied.';$('#error').className='message';$('#error').classList.remove('hidden');setTimeout(()=>$('#error').classList.add('hidden'),1800)}catch{prompt('Copy this link:',u.href)}};
$('#poiBtn').onclick=()=>{if(!result){$('#poiOut').textContent='Waiting for analysis.';scheduleSolve(0);return}const x=+$('#poi').value;if(!Number.isFinite(x)||x<0||x>len()){$('#poiOut').textContent='Enter a position within the beam.';return}const d=result.diagrams||{},pick=a=>{const s=getSeries(d,a);return s.length?s.reduce((best,p)=>Math.abs(p.x-x)<Math.abs(best.x-x)?p:best,s[0]):null};const v=pick(['shear','sfd','V']),m=pick(['moment','bmd','M']),df=pick(['deflection','displacement','delta','y']);$('#poiOut').innerHTML=`x = <b>${fmt(x)} ${unitText('length')}</b><br>Shear = <b>${v?fmt(v.y)+' '+unitText('force'):'—'}</b><br>Moment = <b>${m?fmt(m.y)+' '+unitText('moment'):'—'}</b><br>Deflection = <b>${df?fmt(df.y)+' '+unitText('defl'):'—'}</b>`};$('#reportBtn').onclick=report;
$$('[data-view]').forEach(b=>b.onclick=()=>{viewMode=b.dataset.view;render()});$('#gridBtn').onclick=()=>{showGrid=!showGrid;render()};$('#dimsBtn').onclick=()=>{showDims=!showDims;render()};$('#resetView').onclick=()=>{zoom=1;panX=0;panY=0;render()};$('#zoomIn').onclick=()=>{zoom=Math.min(1.8,+(zoom+.1).toFixed(2));render()};$('#zoomOut').onclick=()=>{zoom=Math.max(.7,+(zoom-.1).toFixed(2));render()};$('#beamViewport').addEventListener('pointerdown',e=>{if(viewMode!=='pan')return;panStart={x:e.clientX,y:e.clientY,px:panX,py:panY};e.currentTarget.setPointerCapture(e.pointerId)});$('#beamViewport').addEventListener('pointermove',e=>{if(!panStart)return;panX=panStart.px+e.clientX-panStart.x;panY=panStart.py+e.clientY-panStart.y;renderBeam()});$('#beamViewport').addEventListener('pointerup',()=>panStart=null);$('#featureToggle').onchange=()=>result&&renderResults();$('#collapseAll').onclick=()=>{$$('#charts .chart').forEach(c=>{c.classList.add('collapsed');const b=c.querySelector('.collapseChart');if(b)b.textContent='Expand'})};
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}});
(function init(){document.documentElement.classList.toggle('dark',dark);const hash=location.hash.match(/^#model=(.+)$/);if(hash){try{model=JSON.parse(decodeURIComponent(escape(atob(hash[1]))));unit=model.units||'SI'}catch{}}render();scheduleSolve(100)})();
